FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        vim \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
